### ISSUE TITLE
How can I integrate project that contains static binary?

### ISSUE THREAD

**Issue by retsohuang** [JamitLabs/Accio#33] opened 2019-04-24 19:56 UTC
Hi there, first of all, big thanks for your hard work 👍 

I've got a question that I'm trying to make [this project](https://github.com/retsohuang/OpenSSL) support Accio but shows contains invalid source files.

Any suggestions?

**Comment by Jeehut** [comment] 2019-04-25 08:07
Can you please copy the full output here? What version of Accio are you using?

**Comment by Jeehut** [comment] 2019-04-25 08:39
Okay, I just tried to install it myself and here's the output:

```bash
✨  Reading package manifest at /Users/Arbeit/Desktop/Demo/Package.swift ...
✨  Generating dependency graph ...
❌  'OpenSSL' /Users/Name/Desktop/Demo/.accio/checkouts/OpenSSL: error: could not find source files for target(s): OpenSSL (iOS); use the 'path' property in the Swift 4 manifest to set a custom target path
An error occurred: dependencyGraphGenerationFailed
```

Seems like the `path` it missing.

**Comment by retsohuang** [comment] 2019-04-25 09:14
I added the `path` property and here's the output:
```shell
✨  Generating dependency graph ...
❌  warning: target 'openssl' in package 'openssl' contains no valid source files
'openssl' /Users/Name/Desktop/Demo/.accio/checkouts/OpenSSL: error: target 'openssl' referenced in product 'openssl' could not be found

An error occurred: dependencyGraphGenerationFailed
```
Accio Version: 0.6.0

**Comment by Jeehut** [comment] 2019-04-25 13:10
@retsohuang Thanks for the feedback. It looks like this is an issue with SwiftPM, see [this thread](https://forums.swift.org/t/is-swiftpm-support-c-language-link-custom-build-static-library-inside-targets/21614) on the Swift Forums or [that bug report](https://bugs.swift.org/browse/SR-8024?page=com.atlassian.jira.plugin.system.issuetabpanels%3Achangehistory-tabpanel) on Swift JIRA. According to the ticket, it's already fixed. So the forum thread might be more useful, as there are some workarounds explained there.

Feel free to test other paths (like `ios/include/openssl`) and also to place a basic `.modulemap` or other suggestions from the thread. If you find a solution, please report it, so we can try to auto-apply that in the temporary checked out files (if possible) or improve the README accordingly.

Sorry that I can't provide a clear solution immediately, but since we're using SwiftPM we also share some of its drawbacks. I will definitely have more detailed look into this sometime later, as this projects goal is to actually fill the gaps of SwiftPM wherever possible, but currently other features have higher priority for me.

In the worst case scenario, you can always combine Accio with other tools like Carthage by only using Carthage for the dependencies that don't work with Accio yet, until the issue is fixed.

**Comment by fredpi** [comment] 2020-10-07 15:51
Closing this, as [Accio is now deprecated](https://github.com/JamitLabs/Accio/pull/92).

**Closed as completed by fredpi** 2020-10-07 15:51 UTC
Labels: bug, question
