### ISSUE TITLE
Unable to install Accio via brew

### ISSUE THREAD

**Issue by Rion-Kaneshiro** [JamitLabs/Accio#38] opened 2019-04-29 13:57 UTC
I tried to install Accio on my company Mac and stumbled upon an issue installing it.

I‘m not quite sure if it relates to Accio directly, though.

Current configuration:

- macOS Mojave 10.14.4 (18E226)
- Xcode 10.2.1 (freshly installed from the App Store)
- Fresh installation of brew
- Swift 5.0.1 (swiftlang-1001.0.82.4 clang-1001.0.46.5)

Running `brew install accio` results in:

```
rion$ brew install accio
Updating Homebrew...
==> Installing accio from jamitlabs/accio
==> Cloning https://github.com/JamitLabs/Accio.git
Updating /Users/abraun/Library/Caches/Homebrew/accio--git
==> Checking out tag 0.6.1
HEAD is now at 6b01bd6 Merge branch 'deploy/0.6.1' into productive
HEAD is now at 6b01bd6 Merge branch 'deploy/0.6.1' into productive
==> make install prefix=/usr/local/Cellar/accio/0.6.1
Last 15 lines from /Users/rion/Library/Logs/Homebrew/accio/01.make:
2019-04-29 15:13:48 +0200
 
make
install
prefix=/usr/local/Cellar/accio/0.6.1
 
dyld: Library not loaded: @rpath/llbuild.framework/Versions/A/llbuild
  Referenced from: /Library/Developer/CommandLineTools/usr/bin/swift-build
  Reason: image not found
make: *** [accio] Abort trap: 6
 
If reporting this issue please do so to (not Homebrew/brew or Homebrew/core):
  jamitlabs/accio
 
/usr/local/Homebrew/Library/Homebrew/utils/github.rb:253:in `raise_api_error': Validation Failed: [{"message"=>"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.", "resource"=>"Search", "field"=>"q", "code"=>"invalid"}] (GitHub::ValidationFailedError)
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:207:in `open_api'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:352:in `search'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:260:in `search_issues'
from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:273:in `issues_for_formula'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:372:in `fetch_issues'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:368:in `issues'
from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:422:in `dump'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:136:in `rescue in <main>'
from /usr/local/Homebrew/Library/Homebrew/brew.rb:36:in `<main>'
```

**Comment by Jeehut** [comment] 2019-04-29 14:21
@Rion-Kaneshiro Thank you for reporting the issue. I tried freshly reinstalling Accio on my machine and it worked, so I can't reproduce the error. Maybe [this solution](https://stackoverflow.com/a/55440343) to a similar problem on SO fixes this?

**Comment by andreas-braun-parship** [comment] 2019-04-30 07:01
@Dschee After a very long reinstallation of Xcode and your proposed solution, it finally installed :)
Seems like the problem has to do with having multiple instances of Xcode installed, like the Beta for example.

Thanks for the help :)

**Comment by Rion-Kaneshiro** [comment] 2019-04-30 07:46
@Dschee After a very long reinstallation of Xcode and your proposed solution, it finally installed :) Seems like the problem has to do with having multiple instances of Xcode installed, like the Beta for example.
Thanks for the help :)

**Comment by Jeehut** [comment] 2019-04-30 08:57
Great to hear that! Closing this then.

**Closed as completed by Jeehut** 2019-04-30 08:57 UTC
Labels: help wanted, question
